# Generated by Django 5.1.8 on 2025-04-20 03:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='affiliate_cta',
            field=models.TextField(blank=True, help_text='Auto-generated affiliate CTAs'),
        ),
        migrations.CreateModel(
            name='AffiliateClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('affiliate_product', models.CharField(max_length=255)),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogpage')),
            ],
            options={
                'indexes': [models.Index(fields=['-click_time'], name='blog_affili_click_t_5032af_idx'), models.Index(fields=['affiliate_product'], name='blog_affili_affilia_589cb4_idx')],
            },
        ),
    ]
