# Generated by Django 5.1.8 on 2025-04-20 01:03

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 4), ('featured_posts', 7), ('categories', 11), ('affiliate_tools', 16)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'default': 'Browse Posts', 'required': False}), 3: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subheading', 1), ('cta_text', 2), ('cta_link', 3)]], {}), 5: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['blog.BlogPage']}), 6: ('wagtail.blocks.ListBlock', (5,), {}), 7: ('wagtail.blocks.StructBlock', [[('posts', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {}), 9: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['blog.BlogIndexPage']}), 10: ('wagtail.blocks.StructBlock', [[('name', 8), ('link', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {}), 12: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 13: ('wagtail.blocks.TextBlock', (), {}), 14: ('wagtail.blocks.URLBlock', (), {}), 15: ('wagtail.blocks.StructBlock', [[('tool_name', 8), ('image', 12), ('description', 13), ('affiliate_link', 14)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {})}),
        ),
    ]
